package Program;
/**
 *
 * @author ruthe & Shreya G
 */
public class IndianaTrail extends javax.swing.JFrame {

    /**
     * Creates new form OrgeonTrail
     */
    public IndianaTrail() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LossDialogBox = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        GameOverText = new javax.swing.JTextField();
        GameOverText1 = new javax.swing.JTextField();
        RestartButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        WinDialogBox = new javax.swing.JDialog();
        WinText = new javax.swing.JTextField();
        RestartButton1 = new javax.swing.JButton();
        ExitButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Shop = new javax.swing.JDialog();
        ShopExit = new javax.swing.JButton();
        BuyBandaid = new javax.swing.JButton();
        BuyGauze = new javax.swing.JButton();
        BuyWater = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CoinsRemaining = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CurrentHealthShop = new javax.swing.JLabel();
        CurrentHealthShopText = new javax.swing.JLabel();
        OutOfCoins = new javax.swing.JDialog();
        jTextField2 = new javax.swing.JTextField();
        OutOfCoinOK = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jButton1 = new javax.swing.JButton();
        ProgressBar = new javax.swing.JProgressBar();
        HealthLabel = new javax.swing.JLabel();
        HealthText = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        GoToShop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        GameOverText.setEditable(false);
        GameOverText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GameOverText.setText("Game Over ");
        GameOverText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameOverTextActionPerformed(evt);
            }
        });

        GameOverText1.setEditable(false);
        GameOverText1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GameOverText1.setText("You Lose");
        GameOverText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameOverText1ActionPerformed(evt);
            }
        });

        RestartButton.setText("Restart");
        RestartButton.setToolTipText("");
        RestartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("What will you do?");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(RestartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExitButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(GameOverText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(GameOverText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GameOverText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GameOverText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RestartButton)
                    .addComponent(ExitButton))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout LossDialogBoxLayout = new javax.swing.GroupLayout(LossDialogBox.getContentPane());
        LossDialogBox.getContentPane().setLayout(LossDialogBoxLayout);
        LossDialogBoxLayout.setHorizontalGroup(
            LossDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(LossDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LossDialogBoxLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        LossDialogBoxLayout.setVerticalGroup(
            LossDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(LossDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LossDialogBoxLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        WinText.setEditable(false);
        WinText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WinText.setText("You Won!");
        WinText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WinTextActionPerformed(evt);
            }
        });

        RestartButton1.setText("Restart");
        RestartButton1.setToolTipText("");
        RestartButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartButton1ActionPerformed(evt);
            }
        });

        ExitButton1.setText("Exit");
        ExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("You Made it to Indiana!");

        javax.swing.GroupLayout WinDialogBoxLayout = new javax.swing.GroupLayout(WinDialogBox.getContentPane());
        WinDialogBox.getContentPane().setLayout(WinDialogBoxLayout);
        WinDialogBoxLayout.setHorizontalGroup(
            WinDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinDialogBoxLayout.createSequentialGroup()
                .addGroup(WinDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WinDialogBoxLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(RestartButton1)
                        .addGap(29, 29, 29)
                        .addComponent(ExitButton1))
                    .addGroup(WinDialogBoxLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(WinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WinDialogBoxLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel7)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        WinDialogBoxLayout.setVerticalGroup(
            WinDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinDialogBoxLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(WinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addGroup(WinDialogBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RestartButton1)
                    .addComponent(ExitButton1))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        Shop.setMinimumSize(new java.awt.Dimension(350, 250));
        Shop.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShopExit.setText("Exit");
        ShopExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopExitActionPerformed(evt);
            }
        });
        Shop.getContentPane().add(ShopExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 176, -1, -1));

        BuyBandaid.setText("Bandaid");
        BuyBandaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyBandaidActionPerformed(evt);
            }
        });
        Shop.getContentPane().add(BuyBandaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 98, -1, -1));

        BuyGauze.setText("Gauze");
        BuyGauze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyGauzeActionPerformed(evt);
            }
        });
        Shop.getContentPane().add(BuyGauze, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 98, -1, -1));

        BuyWater.setText("Water");
        BuyWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyWaterActionPerformed(evt);
            }
        });
        Shop.getContentPane().add(BuyWater, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 98, -1, -1));

        jLabel2.setText("Coins Available");
        Shop.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        CoinsRemaining.setText("7");
        Shop.getContentPane().add(CoinsRemaining, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 39, -1));

        jLabel3.setText("1");
        Shop.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 125, -1, -1));

        jLabel4.setText("2");
        Shop.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 125, 23, -1));

        jLabel5.setText("3");
        Shop.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 125, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("SHOP");
        Shop.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 17, -1, -1));

        CurrentHealthShop.setText("Current Health");
        Shop.getContentPane().add(CurrentHealthShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        CurrentHealthShopText.setText("jLabel7");
        Shop.getContentPane().add(CurrentHealthShopText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.setText("You cannot afford this");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        OutOfCoinOK.setText("OK");
        OutOfCoinOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutOfCoinOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OutOfCoinsLayout = new javax.swing.GroupLayout(OutOfCoins.getContentPane());
        OutOfCoins.getContentPane().setLayout(OutOfCoinsLayout);
        OutOfCoinsLayout.setHorizontalGroup(
            OutOfCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutOfCoinsLayout.createSequentialGroup()
                .addGroup(OutOfCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OutOfCoinsLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(OutOfCoinOK))
                    .addGroup(OutOfCoinsLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        OutOfCoinsLayout.setVerticalGroup(
            OutOfCoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutOfCoinsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(OutOfCoinOK)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(635, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 79, -1, -1));

        jButton1.setText("Forward");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 259, -1, -1));

        ProgressBar.setString("0");
        ProgressBar.setStringPainted(true);
        getContentPane().add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 122, 527, -1));

        HealthLabel.setText("Health");
        getContentPane().add(HealthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        HealthText.setEditable(false);
        HealthText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HealthText.setText("100");
        HealthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthTextActionPerformed(evt);
            }
        });
        getContentPane().add(HealthText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 71, -1));

        Title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("The Indiana Trail");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 43, 412, -1));

        GoToShop.setText("Shop");
        GoToShop.setActionCommand("ToShop");
        GoToShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToShopActionPerformed(evt);
            }
        });
        getContentPane().add(GoToShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Progress");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 100, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

Player player = new Player();
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if (player.isGameOn)
            {
            player.moveForward();
            int p = player.p.getValue();
            //System.out.println("p int value " + p);

            String y=Integer.toString(player.p.getValue());
           
            ProgressBar.setValue(player.p.getValue()); 
            ProgressBar.setString(y);

            //String p2=Integer.toString(p);
            //PTextFeild.setText(p2);  //this was for troubleshooting

            if (player.h.getValue()>0){
                String w=Integer.toString(player.h.getValue());
                HealthText.setText(w);}
            else
            {
                HealthText.setText("Dead");
                p=0;
                String p3=Integer.toString(p);
                //PTextFeild.setText(p3); //was for troubleshooting

                LossDialogBox.setSize(300,300);
                LossDialogBox.setVisible(true);
                
            }
            
            if (player.p.getValue()>=100 && player.h.getValue()>0)
            {
                WinDialogBox.setSize(300,300);
                WinDialogBox.setVisible(true);
                
            }
        }
       
        else
        {
            LossDialogBox.setSize(300,300);
            LossDialogBox.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HealthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HealthTextActionPerformed

    private void GameOverTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameOverTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GameOverTextActionPerformed

    private void GameOverText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameOverText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GameOverText1ActionPerformed

    private void RestartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartButtonActionPerformed

     resetGame();
                
    }//GEN-LAST:event_RestartButtonActionPerformed
    private void resetGame()
    {
        player.reset();
        //set 
        LossDialogBox.hide();

        ProgressBar.setValue(player.p.getValue()); 
        ProgressBar.setString(player.p.getValueInStr());

        HealthText.setText(player.h.getValueInStr());

        CoinsRemaining.setText(player.c.getValueInStr());
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void WinTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WinTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WinTextActionPerformed

    private void RestartButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartButton1ActionPerformed

        resetGame();
    }//GEN-LAST:event_RestartButton1ActionPerformed

    private void ExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton1ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_ExitButton1ActionPerformed

    private void GoToShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToShopActionPerformed

        String w=Integer.toString(player.h.getValue());
        HealthText.setText(w);
        CurrentHealthShopText.setText(w);
        Shop.setSize(250,300);
        
        Shop.setVisible(true);
    }//GEN-LAST:event_GoToShopActionPerformed

    private void BuyGauzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyGauzeActionPerformed

        if (player.c.getValue()>=3)
        {
            player.buyGauze();
            CoinsRemaining.setText(player.c.getValueInStr());
            HealthText.setText(player.h.getValueInStr());
            CurrentHealthShopText.setText(player.h.getValueInStr());
        }
        else
        {
            OutOfCoins.setSize(500,250);
            OutOfCoins.setVisible(true);
        }
    }//GEN-LAST:event_BuyGauzeActionPerformed

    private void BuyBandaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyBandaidActionPerformed

        if (player.c.getValue()>=2)
        {
            player.buyBandaid();
            
            CoinsRemaining.setText(player.c.getValueInStr());
            HealthText.setText(player.h.getValueInStr());
            CurrentHealthShopText.setText(player.h.getValueInStr());
        }
        else
        {
            OutOfCoins.setSize(500,250);
            OutOfCoins.setVisible(true);
        }
        
    }//GEN-LAST:event_BuyBandaidActionPerformed

    private void ShopExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopExitActionPerformed

        Shop.hide();

        
    }//GEN-LAST:event_ShopExitActionPerformed

    private void BuyWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyWaterActionPerformed

        if (player.c.getValue()>=1)
        {
            player.buyWater();
            
            CoinsRemaining.setText(player.c.getValueInStr());
            HealthText.setText(player.h.getValueInStr());
            CurrentHealthShopText.setText(player.h.getValueInStr());
        }
        else
        {
            OutOfCoins.setSize(500,250);
            OutOfCoins.setVisible(true);
        }
    }//GEN-LAST:event_BuyWaterActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void OutOfCoinOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutOfCoinOKActionPerformed
        // TODO add your handling code here:
        OutOfCoins.hide();
    }//GEN-LAST:event_OutOfCoinOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndianaTrail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndianaTrail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndianaTrail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndianaTrail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndianaTrail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuyBandaid;
    private javax.swing.JButton BuyGauze;
    private javax.swing.JButton BuyWater;
    private javax.swing.JLabel CoinsRemaining;
    private javax.swing.JLabel CurrentHealthShop;
    private javax.swing.JLabel CurrentHealthShopText;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ExitButton1;
    private javax.swing.JTextField GameOverText;
    private javax.swing.JTextField GameOverText1;
    private javax.swing.JButton GoToShop;
    private javax.swing.JLabel HealthLabel;
    private javax.swing.JTextField HealthText;
    private javax.swing.JDialog LossDialogBox;
    private javax.swing.JButton OutOfCoinOK;
    private javax.swing.JDialog OutOfCoins;
    public javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton RestartButton;
    private javax.swing.JButton RestartButton1;
    private javax.swing.JDialog Shop;
    private javax.swing.JButton ShopExit;
    private javax.swing.JLabel Title;
    private javax.swing.JDialog WinDialogBox;
    private javax.swing.JTextField WinText;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    
}


